name: DQNAgent
args:
  recorder_config:
    memory_size: 1000000
    state_width: &state_width 84
    state_height: &state_height 84
    state_length: &state_length 4
    batch_size: &batch_size 32

  q_network_config:
    model_name: vanilla_dqn
    parameter_file: null
    state_width: *state_width
    state_height: *state_height
    state_length: *state_length
    args:
      discount_rate: 0.99
      # Divide reward befor clipping
      scale_reward: 1.0
      # reward is clipped between the following min and max
      min_reward: -1.0
      max_reward: 1.0
      # error between predicted Q value and target Q value is clipped by the following min and max
      min_delta: -1.0
      max_delta: 1.0


  optimizer_config:
    name: NeonRMSProp
    args:
      decay: 0.95
      epsilon: 0.000001
      learning_rate: 0.00025

  action_config:
    # Exploration period in which exploration rate is annealed.
    exploration_period: 500
    initial_exploration_rate: 1.0
    terminal_exploration_rate: 0.1

  training_config:
    # Trainig starts after this number of frames are recorded
    train_start: 400

    # Train network every this number of observations are made
    train_frequency: 4

    # Sync networks every this number of observationa are made
    sync_frequency: 20
    n_samples: *batch_size

  save_config:
    # Save network parameter every once after this #episodes
    interval: 5
    saver_config:
      output_dir: &output_dir results
      max_to_keep: 10
      keep_every_n_hours: 1.0
      prefix: DQN

  summary_config:
    # Summarize network every once after this #episodes
    interval: 5
    writer_config:
      output_dir: *output_dir
