alias:
  memory_size: &memory_size 25000
  width: &width 84
  height: &height 84
  stack: &stack 4
  batch: &batch 32
  save_dir: &save_dir results
  save_prefix: &save_prefix DQN_integration_test
  initial_parameter: &initial_parameter example/space_invaders_vanilla_dqn_99000.h5

typename: DQNAgent
args:
  record_config:
    sort_frequency: -1
    stack: *stack

  recorder_config:
    buffer_size: 10
    sample_size: *batch
    priority: 0.0
    importance: 0.0

  model_config:
    model_file: example/vanilla_dqn.yml
    initial_parameter: *initial_parameter
    input_channel: *stack
    input_height: *height
    input_width: *width

  q_network_config:
    typename: DeepQLearning
    args:
      q_learning_config:
        discount_rate: 0.99
        # reward is clipped between the following min and max
        min_reward: -1.0
        max_reward: 1.0
      optimizer_config:
        typename: NeonRMSProp
        args:
          decay: 0.95
          epsilon: 0.000001
          learning_rate: 0.00025
      clip_grads:
        clip_norm: 10

  saver_config:
    output_dir: *save_dir
    max_to_keep: 10
    keep_every_n_hours: 1.0
    prefix: *save_prefix

  save_config:
    # Save network parameter every once after this #trainings
    # Giving non-positive value effectively disable save functionality
    interval: -1

  summary_writer_config:
    output_dir: *save_dir

  summary_config:
    # Summarize network every once after this #trainings
    # Giving non-positive value effectively disable save functionality
    interval: -1

  action_config:
    method: linear
    duration: 0
    epsilon_init: 0.05
    epsilon_term: 0.05

  training_config:
    # Training starts after this number of transitions are recorded
    # Giving negative value effectively disable training and network sync
    train_start: -1
    # Train network every this number of observations are made
    train_frequency: 4
    # Sync networks every this number of observations are made
    sync_frequency: 10000
    n_samples: *batch
