version: 2
executorType: docker
containerInfo:
  - image: mthrok/luchador-base:20170215_tf1
    env:
      - COUNT_INTEGRATION_COVERAGE=true
stages:
  build:
    workDir: /src
    steps:
      - type: checkout
      - type: shell
        name: Install Luchador
        command: |
          python setup.py download_ale --output-dir=luchador/env/ale/rom
          pip install -e .
      - type: shell
        name: Print Version
        command: |
          g++ --version
          python -c "import numpy;print('NumPy:', numpy.__version__)"
          python -c "import scipy;print('SciPy:', scipy.__version__)"
          python -c "import theano;print('Theano:', theano.__version__)"
          python -c "import tensorflow;print('Tensorflow:', tensorflow.__version__)"
          python -c "import luchador;print('luchador:', luchador.__version__)"
      # Unit Test
      - type: shell
        name: Theano Unit Test
        command: LUCHADOR_NN_BACKEND=theano     LUCHADOR_NN_CONV_FORMAT=NCHW coverage run --parallel-mode setup.py test
      - type: shell
        name: Tensorflow Unit Test
        command: LUCHADOR_NN_BACKEND=tensorflow LUCHADOR_NN_CONV_FORMAT=NHWC coverage run --parallel-mode setup.py test
      # Integration Test
      - type: shell
        name: Serialization Test
        command: ./tests/integration/run_serialization_tests.sh
      - type: shell
        name: Initializer Numerical Compatibility Test
        command: ./tests/integration/run_initializer_compatibility_test.sh
      - type: shell
        name: Layer Numerical Compatibility Test
        command: ./tests/integration/run_layer_numerical_compatibility_tests.sh
      - type: shell
        name: Optimizer Numerical Compatibility Test
        command: ./tests/integration/run_optimizer_numerical_compatibility_tests.sh
      - type: shell
        name: Server Client Test
        command: ./tests/integration/test_server_client/run_server_client.sh
      - type: shell
        name: Manager Server Test
        command: ./tests/integration/test_server_client/run_manager_server.sh
      - type: shell
        name: Environment Tests
        command: ./tests/integration/run_envs.sh
      - type: shell
        name: DQN Theano 32 bit
        command: LUCHADOR_NN_BACKEND=theano LUCHADOR_NN_CONV_FORMAT=NCHW THEANO_FLAGS='floatX=float32' ./tests/integration/run_dqn.sh
      - type: shell
        name: DQN Theano 64 bit
        command: LUCHADOR_NN_BACKEND=theano LUCHADOR_NN_CONV_FORMAT=NCHW THEANO_FLAGS='floatX=float64' ./tests/integration/run_dqn.sh
      - type: shell
        name: DQN TensorFlow
        command: LUCHADOR_NN_BACKEND=tensorflow LUCHADOR_NN_CONV_FORMAT=NHWC LUCHADOR_NN_DTYPE=float32 ./tests/integration/run_dqn.sh
      # Style check
      - type: shell
        name: Style Check
        command: |
          flake8 luchador
          flake8 tests
      # Report coverage
      - type: shell
        name: Report Coverage
        command: ./cci_script/report_codacy_test_coverage.sh
      # Build doc and push to gh-pages
      - type: shell
        name: Build Doc
        command: |
          xvfb-run -s "-screen 0 1400x900x24" ./cci_script/build_docs.sh
          # ./cci_script/push_docs.sh
