classifier: &classifier
  typename: Sequential
  args:
    name: classifier
    input_config:
      typename: Input
      reuse: True
      name: input_image
    layer_configs:
      - typename: Conv2D
        args: &conv2d_1
          n_filters: 32
          filter_width: 5
          filter_height: 5
          strides: 2
          padding: same
          scope: layer1/conv2D
      - typename: LeakyReLU
        args:
          scope: layer1/ReLU
          alpha: 0.2
          train: True
      #====================
      - typename: BatchNormalization
        args:
          scope: layer2/BN
      #====================
      - typename: Conv2D
        args: &conv2d_2
          n_filters: 64
          filter_width: 5
          filter_height: 5
          strides: 2
          padding: same
          scope: layer3/conv2D
      - typename: LeakyReLU
        args:
          scope: layer3/ReLU
          alpha: 0.2
          train: True
      #====================
      - typename: BatchNormalization
        args:
          scope: layer4/BN
      #====================
      - typename: Conv2D
        args:
          << : *conv2d_2
          scope: layer5/conv2D
      - typename: LeakyReLU
        args:
          scope: layer5/ReLU
          alpha: 0.2
          train: True
      #====================
      - typename: BatchNormalization
        args:
          scope: layer6/BN
      #===================
      - typename: Flatten
        args:
          scope: layer7/Flatten
      #===================
      - typename: Dense
        args:
          scope: layer8/Dense
          n_nodes: 10
          
error: &error
  typename: Graph
  args:
    name: error
    node_configs:
      - typename: Anonymous
        args:
          scope: label
          exp: one_hot(x, {n_classes})
        input_config:
          typename: Input
          reuse: True
          name: label
      - typename: SoftmaxCrossEntropy
        args:
          scope: error
        input_config:
          target:
            typename: Tensor
            name: label/output
          prediction:
            typename: Model
            name: classifier
            fetch: output
    output_config:
      typename: Tensor
      name: error/output

optimization: &optimization
  typename: Graph
  args:
    name: optimization
    node_configs:
      - typename: Adam
        args:
          learning_rate: 0.01
        input_config:
          loss:
            typename: Model
            name: error
            fetch: output
          wrt:
            typename: Model
            name: classifier
            fetch: parameter

typename: Container
args:
  input_config:
    data:
      typename: Input
      args:
        name: input_image
        shape: {input_shape}
    label:
      typename: Input
      args:
        name: label
        shape: [{batch_size}]
        dtype: int64
  output_config:
    error:
      typename: Model
      name: error
      fetch: output
  model_configs:
    - << : *classifier
      name: classifier
    - << : *error
      name: error
    - << : *optimization
      name: optimization
