test-steps: &test-steps
  - checkout
  - run:
      name: Install Luchador
      command: pip install -e .
  - run:
      name: Print Version
      command: |
        g++ --version
        python -c "import numpy;print('NumPy:', numpy.__version__)"
        python -c "import scipy;print('SciPy:', scipy.__version__)"
        python -c "import theano;print('Theano:', theano.__version__)"
        python -c "import tensorflow;print('Tensorflow:', tensorflow.__version__)"
        python -c "import luchador;print('luchador:', luchador.__version__)"
  # Unit Test
  - run:
      name: Theano Unit Test
      command: LUCHADOR_NN_BACKEND=theano     LUCHADOR_NN_CONV_FORMAT=NCHW coverage run setup.py test
  - run:
      name: Tensorflow Unit Test
      command: LUCHADOR_NN_BACKEND=tensorflow LUCHADOR_NN_CONV_FORMAT=NHWC coverage run setup.py test
  # Integration Test
  - run:
      name: Initializer Numerical Compatibility Test
      command: ./tests/integration/run_initializer_compatibility_test.sh
  - run:
      name: Layer Numerical Compatibility Test
      command: ./tests/integration/run_layer_numerical_compatibility_tests.sh
  - run:
      name: Optimizer Numerical Compatibility Test
      command: ./tests/integration/run_optimizer_numerical_compatibility_tests.sh
  # Save coverage files
  - persist_to_workspace:
      root: ./
      paths:
        - .coverage.*

example1-steps: &example1-steps
  - checkout
  - run:
      name: Install Luchador
      command: pip install -e .
  # Run examples
  - run:
      name: Examples Theano 32 bit
      command: LUCHADOR_NN_BACKEND=theano THEANO_FLAGS='floatX=float32' ./tests/integration/run_examples.sh
  # Save coverage files
  - persist_to_workspace:
      root: ./
      paths:
        - .coverage.*

example2-steps: &example2-steps
  - checkout
  - run:
      name: Install Luchador
      command: pip install -e .
  # Run examples
  - run:
      name: Examples Theano 64 bit
      command: LUCHADOR_NN_BACKEND=theano THEANO_FLAGS='floatX=float64' ./tests/integration/run_examples.sh
  # Save coverage files
  - persist_to_workspace:
      root: ./
      paths:
        - .coverage.*

example3-steps: &example3-steps
  - checkout
  - run:
      name: Install Luchador
      command: pip install -e .
  # Run examples
  - run:
      name: Examples Tensorflow
      command: LUCHADOR_NN_BACKEND=tensorflow LUCHADOR_NN_CONV_FORMAT=NHWC LUCHADOR_NN_DTYPE=float32 ./tests/integration/run_examples.sh
  # Save coverage files
  - persist_to_workspace:
      root: ./
      paths:
        - .coverage.*

python27_config: &python27_config
    docker:
      - image: mthrok/luchador-base:20170717
        env:
          - COUNT_INTEGRATION_COVERAGE=true
    working_directory: ~/luchador
        
        
python36_config: &python36_config
    docker:
      - image: mthrok/luchador-base-py36:latest
        env:
          - COUNT_INTEGRATION_COVERAGE=true
    working_directory: ~/luchador
        
        
version: 2
jobs:
  python27-test:
    << : *python27_config
    steps:
      *test-steps

  python27-example1:
    << : *python27_config
    steps:
      *example1-steps

  python27-example2:
    << : *python27_config
    steps:
      *example2-steps

  python27-example3:
    << : *python27_config
    steps:
      *example3-steps

  python36-test:
    << : *python36_config
    steps:
      *test-steps

  python36-example1:
    << : *python36_config
    steps:
      *example1-steps

  python36-example2:
    << : *python36_config
    steps:
      *example2-steps

  python36-example3:
    << : *python36_config
    steps:
      *example3-steps

  style-check:
    <<: *python27_config
    steps:
      - checkout
      - run:
          name: Style Check
          command: |
            flake8 luchador
            flake8 tests
    
  post-process:
    << : *python27_config
    steps:
      - checkout
      # Get coverage files
      - attach_workspace:
          at: ./
      # Report coverage
      - run:
          name: Report Coverage
          command: ./.circleci/report_codacy_test_coverage.sh
      # Build doc and push to gh-pages
      # - run:
      #     name: Install Luchador
      #     command: pip install -e .
      # - run:
      #     name: Build Doc
      #     command: |
      #       xvfb-run -s "-screen 0 1400x900x24" ./.circleci/build_docs.sh
      #       ./.circleci/push_docs.sh

workflows:
  version: 2
  build:
    jobs:
      - style-check
      - python27-test
      - python27-example1:
          requires:
            - python27-test
      - python27-example2:
          requires:
            - python27-test
      - python27-example3:
          requires:
            - python27-test
      - post-process:
          requires:
            - python27-example1
            - python27-example2
            - python27-example3

      - python36-test
      - python36-example1:
          requires:
            - python36-test
      - python36-example2:
          requires:
            - python36-test
      - python36-example3:
          requires:
            - python36-test
